# Generated by Django 4.2.6 on 2023-10-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='employer',
        ),
        migrations.DeleteModel(
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Rider',
        ),
    ]
