# Generated by Django 4.2.6 on 2023-10-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='id',
        ),
        migrations.AddField(
            model_name='rider',
            name='brand',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='rider',
            name='model',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='rider',
            name='number_plate',
            field=models.CharField(default='KMTC 123G', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='offence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offence',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rider'),
        ),
        migrations.DeleteModel(
            name='vehicle',
        ),
    ]
