# Generated by Django 4.2.6 on 2023-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_rider_gender_remove_rider_id_rider_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offence',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
