# Generated by Django 4.2.6 on 2023-10-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_offence_latitude_offence_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='speed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offence',
            name='speed_limit',
            field=models.IntegerField(null=True),
        ),
    ]
