# Generated by Django 4.2.6 on 2023-11-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_offence_speed_offence_speed_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offence',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
