# Generated by Django 4.2.6 on 2023-11-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_offence_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offence',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
